### ISSUE TITLE
Doesn't compile.

### ISSUE THREAD

**Issue by wt** [VilNeo/patch-xml#1]
I get this error when trying to install the crate:
```
...
error[E0557]: feature has been removed
 --> /home/wt/.cargo/registry/src/github.com-1ecc6299db9ec823/patch-xml-0.0.3/src/lib.rs:1:12
  |
1 | #![feature(external_doc)]
  |            ^^^^^^^^^^^^ feature has been removed
  |
  = note: use #[doc = include_str!("filename")] instead, which handles macro invocations
...
```

**Comment by VilNeo** [comment]
Thank you very much for your feedback.
I've just merged the PR from mriise.
Unfortunately, I came to the conclusion, that this initial attempt was not sufficient for my needs.
For this reason I will prune already published versions on crates.io to avoid confusion here.
Within the next weeks I will also remove this repository for the same reason.
I will publish a new version eventually when it turns out to be usable and stable.
I am very sorry to disappoint here.
